/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-09-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class StaticValuesUtil {
    public static final String COUNTRY_INDIA = 'India';
    public static final String COUNTRY_CODE_INDIA = 'IN';
    public static final String STATE_GUJARAT = 'Gujarat';
    public static final String STATE_CODE_GUJARAT = 'GJ';
    public static final String DEPARTMENT_FIELD = 'department';
    public static final String DEPARTMENT_MASTERS = 'Masters';
    public static final String DEPARTMENT_UNDERGRAD = 'Undergraduation';
    public static final String DEPARTMENT_PHD = 'Phd';
    public static final String FIELD_PHONE = 'phone';
    public static final String FIELD_EMAIL = 'email';
    public static final String TYPE_OF_FORM_FIELD = 'typeOfForm';
    public static final String FIELD_FIRST_NAME = 'firstName';
    public static final String FIELD_LAST_NAME = 'lastName';
    public static final String FIELD_ADMISSION_YEAR = 'admissionYear';
    public static final String FIELD_PROGRAMME_INTERESTED = 'programmeInterestedIn';
    public static final String FIELD_COLLEGE_UNIVERSITY = 'collegeOrUniversity';
    public static final String FIELD_COUNTRY = 'country';
    public static final String FIELD_CITY = 'city';
    public static final String FIELD_STATE = 'state';
    public static final String FIELD_AREAS = 'areas';
    public static final String FIELD_I_AM = 'iam';
    public static final String FIELD_CLASS = 'class';
    public static final String FIELD_ORGANISATION = 'organisation';
    public static final String TYPE_WEBSITE_UG_QUERIES = 'Website_UGQueries';
    public static final String VALUE_IAM_STUDENT = 'Student';
    public static final String VALUE_IAM_FOAU = 'Friend of Ahmedabad University';
    public static final String VALUE_IAM_PARENT = 'Parent';
    public static final String VALUE_IAM_EDUCATOR = 'Educator';
    public static final String VALUE_IAM_ORGANISATION = 'organisation';
    public static final String FIELD_CAMPAIGN_NAME = 'campaignName';
    public static final String FIELD_UTM_LINK = 'utmLink';
    public static final String FIELD_CAMPAIGN_SOURCE = 'campaignSource';
    public static final String FIELD_CAMPAIGN_MEDIUM = 'campaignMedium';
    public static final String FIELD_PHD_SCHOOL_NAME = 'phdSchoolName';
    }